HogarDeEnsuenio/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import actualizar_usuario,actualizar_inmueble,eliminar_inmueble, registro_usuario,index,detalle_inmueble,cambiar_estado_solicitud, generar_solicitud_arriendo,crear_inmueble,solicitudes_arrendador,dashboard
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static

from HogarDeEnsuenio import settings

urlpatterns = [
    path('', index, name='index'),
    path('admin/', admin.site.urls),
    path('registro/', registro_usuario, name='registro_usuario'),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='index'), name='logout'),
    path('inmueble/<int:id>/',detalle_inmueble , name='detalle'),
    path('inmuebles/<int:id>/generar-solicitud/', generar_solicitud_arriendo, name='generar_solicitud_arriendo'),
    path('inmueble/<int:id>/editar_inmueble',actualizar_inmueble, name='editar_inmueble'),
    path('inmueble/<int:id>/eliminar_inmueble',eliminar_inmueble, name='eliminar_inmueble'),
    path('alta-inmueble/', crear_inmueble, name='alta_inmueble'),
    path('solicitudes/', solicitudes_arrendador, name='solicitudes_arrendador'),
    path('dashboard/', dashboard, name='dashboard'),
    path('perfil/', actualizar_usuario, name='actualizar_usuario'),
    path('cambiar_estado_solicitud/<int:solicitud_id>/', cambiar_estado_solicitud, name='cambiar_estado_solicitud'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.\
    
    
    
class Region(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self):
        return self.nombre
    
    
class Comuna(models.Model):
    nombre = models.CharField(max_length=100)
    region = models.ForeignKey(Region, related_name='comunas', on_delete=models.CASCADE)
    def __str__(self):
        return self.nombre

class Usuario(User):
    TIPO_USUARIO_CHOISES = [
        ('arrendatario', 'Arrendatario'),
        ('arrendador', 'Arrendador'),
    ]
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=50)
    rut = models.CharField(max_length=10, unique=True)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=13)
    tipo_usuario = models.CharField(max_length=20, choices=TIPO_USUARIO_CHOISES)
    correo_electronico = models.EmailField(unique=True, default='correo@correo.cl') 

    def __str__(self):
        return f"{self.nombres} {self.apellidos}"
        
        
        
class Inmueble(models.Model):
    TIPO_INMUEBLE_CHOISES = [
        ('casa','Casa'),
        ('departamento','Departamento'),
        ('parcela','Parcela'),
    ]
    nombre=models.CharField(max_length=50)
    direccion=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=50)
    imagen =models.ImageField(upload_to='',null=True, blank=True)
    precio=models.DecimalField(max_digits=10, decimal_places=0)
    comuna = models.ForeignKey(Comuna, related_name='inmuebles', on_delete=models.CASCADE)
    disponible=models.BooleanField(default=True)
    m2_construidos = models.DecimalField(max_digits=10, decimal_places=2)
    m2_terreno = models.DecimalField(max_digits=10, decimal_places=2)
    cantidad_estacionamientos = models.PositiveIntegerField()
    cantidad_habitaciones = models.PositiveIntegerField()
    cantidad_banos = models.PositiveIntegerField()
    tipo_de_inmueble=models.CharField(max_length=12, choices=TIPO_INMUEBLE_CHOISES)
    propietario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    

    
    def __str__(self) -> str:
        return f"{self.nombre}"
    


class SolicitudArriendo(models.Model):
    TIPO_ESTADO_CHOISES = [
        ('pendiente','Pendiente'),
        ('aceptado','Aceptado'),
        ('rechazado','Rechazado'),   
    ]
     
    arrendatario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    inmueble = models.ForeignKey(Inmueble, on_delete=models.CASCADE)
    mensaje = models.TextField(blank=True)
    estado =models.CharField(choices=TIPO_ESTADO_CHOISES, default='pendiente')
    
    def __str__(self):
        return f"Solicitud de {self.inmueble.nombre} por {self.arrendatario.nombres} {self.arrendatario.apellidos}"    

app/templates/alta_inmueble.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}
<h2>Alta de Inmueble</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Mi Sitio Web{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Agregar aquí tus enlaces a archivos CSS externos, fuentes, etc. -->
</head>
<body>
<nav>      
{% block 'navbar' %}
{% include "includes/navbar.html" %}
{% endblock 'navbar' %}
</nav>  


<main>
    {% block content %}
    {% endblock %}
</main>


{% block footer %}
{% include "includes/footer.html" %}
{% endblock footer %}


{% include "includes/scripts.html" %}

</body>
</html>

app/templates/dashboard_arrendador.html
{% extends "base.html" %}
{% block content %}
  {% if user.usuario.tipo_usuario == 'arrendador' %}

  <h2>Tus Inmuebles</h2>
  <section class="container mx-auto pt-5">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
      {% for inm in inmuebles %}
        <div class="col">
          <div class="card h-100">
              <img class="card-img-top" src="/media/{{inm.imagen}}" alt="Card image cap">
            </a>
            <div class="card-body">
              <h5 class="card-title">{{ inm.name }}</h5>
              <p class="card-text text-justify">
                  {% if inm.descripcion|length > 100 %}
                      {{ inm.descripcion|slice:":100" }}... <a href="">descripcion</a>
                  {% else %}
                      {{ inm.descripcion}}
                  {% endif %}
              </p>
          </div>
            <div class="card-footer">
              <a href="{% url 'detalle' inm.id %}">detalle del inmueble</a>
            </div>
          </div>
        </div>
      {% endfor %}  
    </div>
  </section>
     <h2>Solicitudes Recibidas</h2>
     <section class="container mx-auto pt-5">
         <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
             {% for solicitud in solicitudes_recibidas %}
             <div class="card text-bg-primary mb-3" style="max-width: 18rem;">
                     <div class="card-header">{{solicitud.estado}}</div>
                     <div class="card-body">
                         <h5 class="card-title">{{ solicitud }}</h5>
                         <p>{{solicitud.mensaje}}</p>
                         {% if solicitud.estado != 'aceptado' %}
                             <form method="post" action="{% url 'cambiar_estado_solicitud' solicitud.id %}">
                                 {% csrf_token %}
                                 <select name="nuevo_estado">
                                     <option value="pendiente">Pendiente</option>
                                     <option value="aceptado">Aceptado</option>
                                     <option value="rechazado">Rechazado</option>
                                 </select>
                                 <button type="submit">Cambiar Estado</button>
                             </form>
                         {% endif %}
                     </div>
                 </div>
             {% endfor %}
         </div>
     </section>
  {% endif %}
{% endblock %}

app/templates/dashboard_arrendatario.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>Dashboard - Arrendatario</h2>
    <form method="GET" action="{% url 'dashboard' %}">
        <label for="region">Región:</label>
        <select name="region" id="region">
            <option value="">Seleccionar Región</option>
            {% for region in regiones %}
                <option value="{{ region.id }}">{{ region.nombre }}</option>
            {% endfor %}
        </select>
        <label for="comuna">Comuna:</label>
        <select name="comuna" id="comuna">
            <option value="">Seleccionar Comuna</option>
            {% for comuna in comunas %}
                <option value="{{ comuna.id }}">{{ comuna.nombre }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filtrar</button>
    </form>
    <h3>Inmuebles Disponibles:</h3>
    <ul>
        <section class="container mx-auto pt-5">
            <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
              {% for inm in inmuebles %}
                <div class="col">
                  <div class="card h-100">
                      <img class="card-img-top" src="/media/{{inm.imagen}}" alt="Card image cap">
                    </a>
                    <div class="card-body">
                      <h5 class="card-title">{{ inm.name }}</h5>
                      <p class="card-text text-justify">
                          {% if inm.descripcion|length > 10 %}
                              {{ inm.descripcion|slice:":10" }}... <a href="">descripcion</a>
                          {% else %}
                              {{ inm.descripcion}}
                          {% endif %}
                      </p>
                  </div>
                    <div class="card-footer">
                      <a href="{% url 'detalle' inm.id %}">detalle del inmueble</a>
                    </div>
                  </div>
                </div>
              {% endfor %}  
            </div>
          </section>
        
    </ul>
    <h3>Solicitudes de Arriendo:</h3>
    <section class="container mx-auto pt-5">
    <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
    {% for solicitud in solicitudes %}
    <div class="card mb-3 {% if solicitud.estado == 'aceptado' %}bg-success{% elif solicitud.estado == 'pendiente' %}bg-warning{% elif solicitud.estado == 'rechazado' %}bg-danger{% else %}bg-secondary{% endif %}" style="max-width: 18rem;"">
      <div class="card-header">{{solicitud.estado}}</div>
      <div class="card-body">
        <h5 class="card-title">{{ solicitud }}</h5>
        <P>{{solicitud.mensaje}}</P>
      </div>
    </div>
    {% endfor %}
    </div>
   </section>
{% endblock %}

app/templates/detalle_inmueble.html
{% extends 'base.html' %}


{% block title %}Página de Inicio{% endblock %}
{% load static %}
{% block content %}
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="/media/{{inmueble.imagen}}">
        <div class="card-body">
          <h5 class="card-title">{{inmueble.nombre}}</h5>
          <p class="card-text">{{inmueble.descripcion}}</p>
          <p>{{inmueble.comuna}}</p>
        </div>
      </div>
    {% if user.usuario.tipo_usuario == 'arrendatario' %}
    <a href="{% url 'generar_solicitud_arriendo' inmueble.id %}">Generar Solicitud de Arriendo</a>
    {% endif %}

    {% if user.usuario.tipo_usuario == 'arrendador' %}
    <a href="{% url 'editar_inmueble' inmueble.id %}" onclick="return confirm('¿editar?');">editar Inmueble</a>
    <a href="{% url 'eliminar_inmueble' inmueble.id %}" onclick="return confirm('¿quieres eliminar?');">eliminar Inmueble</a>
    {% endif %}
    
{% endblock %}

app/templates/editar_inmueble.html
{% block title %}Página de Inicio{% endblock %}

{% block content %}
<h2>editar Inmueble</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">editar</button>
</form>
{% endblock %}

app/templates/eliminar_inmueble.html
{% block title %}Página de Inicio{% endblock %}

{% block content %}
<h2>Eliminar Inmueble</h2>
    <p>¿Estás seguro de que deseas eliminar el inmueble "{{ inmueble.nombre }}"?</p>
    <form method="post">
        {% csrf_token %} 
        <button type="submit">Eliminar</button>
    </form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}
{% load static %}
{% block content %}
    <h2>Bienvenido a mi sitio web!</h2>
    <p>Este es el contenido de la página de inicio.</p>
    <section class="container mx-auto pt-5">
      <div class="row row-cols-1 row-cols-md-3 row-cols-lg-5 g-4">
        {% for inm in inmuebles %}
          <div class="col">
            <div class="card h-100">
                <img class="card-img-top" src="media/{{inm.imagen}}" alt="Card image cap">
              </a>
              <div class="card-body">
                <h5 class="card-title">{{ inm.name }}</h5>
                <p class="card-text text-justify">
                    {% if inm.descripcion|length > 100 %}
                        {{ inm.descripcion|slice:":100" }}... <a href="">descripcion</a>
                    {% else %}
                        {{ inm.descripcion}}
                    {% endif %}
                </p>
            </div>
              <div class="card-footer">
                <a href="{% url 'detalle' inm.id %}">detalle del inmueble</a>
              </div>
            </div>
          </div>
        {% endfor %}  
      </div>
    </section>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h2>Iniciar sesión</h2>
  <form method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">Nombre de usuario:</label>
      <input type="text" class="form-control" id="username" name="username" required>
    </div>
    <div class="form-group">
      <label for="password">Contraseña:</label>
      <input type="password" class="form-control" id="password" name="password" required>
    </div>
    <button type="submit" class="btn btn-primary">Iniciar sesión</button>
  </form>
</div>
{% endblock %}

app/templates/perfil.html
{% extends 'base.html' %}
{% block content %}
    <h2>Actualizar Datos</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Actualizar</button>
    </form>
{% endblock %}

app/templates/registro_usuario.html
<!-- registro_usuario.html -->
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}  
<div class="container">
    <h2>Registrarse</h2>
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_username">Username:</label>
            <input type="text" class="form-control" id="id_username" name="username" required>
        </div>
        <div class="form-group">
            <label for="id_password">Password:</label>
            <input type="password" class="form-control" id="id_password" name="password" required>
        </div>
        <div class="form-group">
            <label for="id_nombres">Nombres:</label>
            <input type="text" class="form-control" id="id_nombres" name="nombres" required>
        </div>
        <div class="form-group">
            <label for="id_apellidos">Apellidos:</label>
            <input type="text" class="form-control" id="id_apellidos" name="apellidos" required>
        </div>
        <div class="form-group">
            <label for="id_rut">Rut:</label>
            <input type="text" class="form-control" id="id_rut" name="rut" required>
        </div>
        <div class="form-group">
            <label for="id_direccion">Direccion:</label>
            <input type="text" class="form-control" id="id_direccion" name="direccion" required>
        </div>
        <div class="form-group">
            <label for="id_telefono">Telefono:</label>
            <input type="tel" class="form-control" id="id_telefono" name="telefono" required>
        </div>
        <div class="form-group">
            <label for="id_correo_electronico">Correo electrónico:</label>
            <input type="email" class="form-control" id="id_correo_electronico" name="correo_electronico" required>
        </div>
        <div class="form-group">
            <label for="id_tipo_usuario">Tipo usuario:</label>
            <select class="form-control" id="id_tipo_usuario" name="tipo_usuario" required>
                <option value="arrendatario">Arrendatario</option>
                <option value="arrendador">Arrendador</option>
            </select>
        </div>
        <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
</div>
{% endblock %}

app/templates/solicitudes_arrendador.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}
{% load static %}
{% block content %}
<h1>Solicitudes Recibidas</h1>
<ul>
    {% for solicitud in solicitudes %}
    <li>
        <p>Arrendatario: {{ solicitud.arrendatario }}</p>
        <p>Inmueble: {{ solicitud.inmueble }}</p>
        <p>Mensaje: {{ solicitud.mensaje }}</p>
    </li>
    {% empty %}
    <li>No hay solicitudes recibidas.</li>
    {% endfor %}
</ul>
   
{% endblock %}

app/templates/ver_solicitud.html
{% extends 'base.html' %}

{% block title %}Página de Inicio{% endblock %}

{% block content %}
    <h2>Bienvenido a mi sitio web!</h2>
    <p>Este es el contenido de la página de inicio.</p>
{% endblock %}